### ISSUE TITLE
I think this should be way bigger than 0.5s

### ISSUE THREAD

**Issue by fiendish** [kids-first/kf-lambda-fileregistry#20]
https://github.com/kids-first/kf-lambda-fileregistry/blob/a9ce15f935a34681fbb1ab5aa73f1f6c642dc03d/service.py#L75

500ms doesn't seem like enough time to bounce multiple requests through s3 and the dataservice without the lambda getting killed somewhere along the way.

**Comment by dankolbman** [comment]
The only work that needs to be done once this condition is met is to invoke the function in aws again. 500ms should be plenty of time.

**Comment by fiendish** [comment]
Yes, but right before the condition is met you could start doing a round of fetching with only 501ms available. The lambda might then get killed in the middle, no?

**Comment by dankolbman** [comment]
That's true. Maybe 2-3s is more reasonable?

**Comment by fiendish** [comment]
Honestly I have no idea. The aws cli sometimes seems to take forever to fetch and tag s3 items on my machine, but how that translates into times on amazon's own systems is anyone's guess. The way I figure it though, you could even make it something wildly high like 30s and be really really safe without losing too much to overhead.
